
import React from 'react';
import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';

interface RatingProps {
  score: number;
  label: string;
}

const RatingBadge: React.FC<RatingProps> = ({ score, label }) => {
  const getColor = (score: number) => {
    switch(score) {
      case 5: return "bg-green-100 text-green-700"; // Excellent
      case 4: return "bg-blue-100 text-blue-700";   // Good
      case 3: return "bg-yellow-100 text-yellow-700"; // Average
      case 2: return "bg-orange-100 text-orange-700"; // Below average
      case 1: return "bg-red-100 text-red-700";     // Poor
      default: return "bg-gray-100 text-gray-700";  // Default
    }
  };

  return (
    <div className="flex flex-col space-y-1">
      <div className="text-xs font-medium">{label}</div>
      <div className={cn("px-2 py-1 rounded-md text-xs font-medium inline-flex items-center justify-center", getColor(score))}>
        {score}/5
      </div>
    </div>
  );
};

const QualityAssurance = () => {
  return (
    <motion.div 
      className="p-5 rounded-xl bg-white shadow-md border border-border"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.1 }}
    >
      <div className="mb-3 flex justify-between items-center">
        <div className="text-sm font-semibold">Quality Assurance</div>
        <div className="text-xs text-muted-foreground">Auto-generated by AI</div>
      </div>
      
      <div className="grid grid-cols-2 gap-4">
        <RatingBadge score={5} label="Clarity" />
        <RatingBadge score={4} label="Difficulty" />
        <RatingBadge score={3} label="Education" />
        <RatingBadge score={5} label="Coverage" />
      </div>
    </motion.div>
  );
};

export default QualityAssurance;
